name: Auto test Recipe_Finder project

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run the app
        id: run-app
        run: |
          npm ci
          PORT=3000 npm run dev &
          sleep 5

      - name: Run integration tests
        run: |
          npm install cypress cypress-json-results
          npx cypress run --env STUDENT_SUBMISSION_URL="http://localhost:3000/"

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sameerbagde92/Recipe_Finder

      - name: Push Docker Image
        run: docker push sameerbagde92/Recipe_Finder

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: [run-tests, build-docker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use the Node.js version that matches your project

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true

  notification:
    name: Send Slack Notification
    needs: [deploy, run-tests]
    runs-on: ubuntu-latest

    if: ${{ always() }}
    steps:
      - name: Send success notification
        if: ${{ needs.deploy.result == 'success' && needs.run-tests.result == 'success' }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: |
            *Success:* The workflow Auto test Recipe_Finder project succeeded. Access the details [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send failure notification
        if: ${{ needs.deploy.result != 'success' || needs.run-tests.result != 'success' }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: |
            *Failure:* The workflow Auto test Recipe_Finder project failed. Access the details [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
